### ISSUE TITLE
Specifying styles to a content script

### ISSUE THREAD

**Issue by avi12** [nonua/chrome-vite-svelte-ts-sass-boilerplate#22]
I need to specify styles in SCSS like so:
```ts
import { defineManifest } from "@crxjs/vite-plugin";

export default defineManifest({
  content_scripts: [
    {
      matches: ["domain"],
      js: ["src/content.ts"],
      css: ["src/content.scss"]
    }
  ]
});
```
Except, Vite won't process `src/content.scss` into `build/src/content.css`

**Comment by Nonua** [comment]
Currently `crxjs` does not support adding the scss in html stylesheet just like regular Svelte project, instead you can import scss directly in [popup `index file`](https://github.com/Nonua/chrome-vite-svelte-ts-sass-boilerplate/blob/master/src/popup/index.ts)

**Comment by Nonua** [comment]
Currently `crxjs` does not support that feature, instead you could add this at the beginning of `content.ts`
```
import 'path/to/content.scss';
```
